import React from "react";
import ReactDOM from "react-dom/client";
import App from "./components/App";
import "./scss/normalize.scss";
import "./scss/reset.scss";
import "./scss/login/LoginContainer.scss";
import "./scss/login/SignUp.scss";
import "./scss/home/Home.scss";
import "./scss/sidebar/Location.scss";
import "./scss/sidebar/OrderHistory.scss";
import "./scss/sidebar/MyInformation.scss";
import "./scss/order/Menu.scss";
import "./scss/order/Basket.scss";
import "./scss/order/Payment.scss";
import "./scss/order/OrderList.scss";
import "./scss/seller/Seller.scss";
import "./scss/error/Error.scss";

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<App />);
